# specify docker as a dependency
sudo: required
services:
  - docker

# build test version to react project
before_install:
  - docker build -t bencotton/react-test -f ./client/Dockerfile.dev ./client

# run tests
script:
  - docker run -e CI=true bencotton/react-test npm test -- --coverage

# build prod versions of all projects
after_success:
  - docker build -t bencotton/multi-client ./client
  - docker build -t bencotton/multi-nginx ./nginx
  - docker build -t bencotton/multi-server ./server
  - docker build -t bencotton/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push all images to docker hub
  - docker push bencotton/multi-client
  - docker push bencotton/multi-nginx
  - docker push bencotton/multi-server
  - docker push bencotton/multi-worker
# tell elastic beanstalk to update
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-093784922600'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY